<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="PRG_PID_CALL" Id="{e7fc84ae-b95c-477c-b1bf-9630c0dddc70}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_PID_CALL
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PRG_PID_CALL">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>