<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="EM_Tank" Id="{f3692e50-4b98-43f6-9336-6d9a3f0032b6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EM_Tank
VAR_INPUT
	
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="EM_Tank">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>